name: Swift CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: macos-13
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Swift version
        run: swift --version

      - name: Cache SPM build
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Resolve
        run: swift package resolve

      - name: Build
        run: swift build -v

      - name: Test (with coverage)
        run: swift test --enable-code-coverage

      - name: Store coverage (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data
          path: .build/debug/codecov/*.json
          if-no-files-found: ignore
          
      - name: Coverage gate (fail if < 80%)
        if: always()
        shell: bash
        run: |
          set -euo pipefail
          swift test --enable-code-coverage
          profdata=$(ls .build/debug/codecov/*.profraw | head -n1 || true)
          if [[ -z "${profdata:-}" ]]; then
            echo "No profraw found"; exit 1
          fi
          xcrun llvm-profdata merge -sparse .build/debug/codecov/*.profraw -o .build/debug/default.profdata
          BIN=$(find .build/debug -name "*Tests.xctest" -type d -maxdepth 2 | head -n1)
          xcrun llvm-cov report "$BIN/Contents/MacOS/$(basename "$BIN" .xctest)" \
            -instr-profile .build/debug/default.profdata > coverage.txt
          cat coverage.txt
          PCT=$(awk '/TOTAL/ {gsub("%",""); print $NF}' coverage.txt)
          PCT=${PCT%.*}
          echo "Coverage: ${PCT}%"
          if [[ "${PCT:-0}" -lt 80 ]]; then
            echo "Coverage below 80%"; exit 1
          fi
      - name: Coverage (overall ≥ 50%)
        run: |
          chmod +x Scripts/coverage-summary.sh
          ./Scripts/coverage-summary.sh 50

      - name: Coverage (core ≥ 80%)
        run: |
          chmod +x Scripts/coverage-core.sh
          ./Scripts/coverage-core.sh 80
