name: Swift CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: macos-13
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Swift version
        run: swift --version

      - name: Cache SPM build
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Resolve
        run: swift package resolve

      - name: Build
        run: swift build -v

      - name: Test (with coverage)
        run: swift test --enable-code-coverage

      - name: Store coverage (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data
          path: .build/debug/codecov/*.json
          if-no-files-found: ignore
