name: Swift CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: macos-13
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.2"

      - name: Swift version
        run: swift --version

      - name: Cache SPM build
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Resolve
        run: swift package resolve

      - name: Build
        run: swift build -v

      - name: Test (with coverage)
        run: swift test --enable-code-coverage

      - name: Store coverage (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data
          path: .build/**/codecov/*.json
          if-no-files-found: ignore

      # ✅ Gate robusto: usa tu script y evita BIN/Contents/MacOS rotos
      - name: Coverage gate (fail if < 80%)
        if: always()
        run: |
          chmod +x Scripts/coverage-summary.sh || true
          ./Scripts/coverage-summary.sh 80

      - name: Coverage (overall ≥ 50%)
        run: |
          chmod +x Scripts/coverage-summary.sh || true
          ./Scripts/coverage-summary.sh 50

      - name: Coverage (core ≥ 80%)
        run: |
          chmod +x Scripts/coverage-core.sh || true
          ./Scripts/coverage-core.sh 80
