name: Regenerate from OpenAPI

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]

concurrency:
  group: regen-openapi
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  regen:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Fetch OpenAPI (single source)
        run: bash Scripts/fetch-openapi.sh

      - name: Regenerate Swift types/client (wrapper)
        run: swift Scripts/generate-from-openapi.swift

      - name: Build & test (with coverage)
        run: swift test --enable-code-coverage

      - name: Create PR with changes
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(openapi): regenerate Swift types & client"
          branch: chore/regen-openapi
          title: "chore(openapi): regenerate Swift types & client"
          body: |
            Automated regeneration from NEAR OpenAPI.
            - Force JSON-RPC POST "/"
            - snake_case → camelCase
            - Build & tests passed in CI
          labels: automated, openapi
          delete-branch: true
