name: Release Please

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # manifest mode: solo necesitas estos dos si ya tienes los archivos en el repo
          config-file: release-please-config.json
          manifest-file: release-please-manifest.json
          # opcional si tu default branch no fuera main:
          # target-branch: main
